---
title: "Data preprocessing"
author: "Health Data Science Unit"
date: "`r date()`"
output: html_document
---


```{r include=FALSE}
library(Seurat)
library(tidyverse)
library(gridExtra)

knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      cache = TRUE,
                      fig.align = TRUE,
                      fig.height = 8,
                      fig.width = 10, 
                      cache.lazy = FALSE)
```

## Adrenal Medulla
        
```{r}
## Loading annotations
adrenal_ann <- read.table('../data/cell_type_annotation_medulla.tsv', sep = '\t',
                          stringsAsFactors = FALSE)
adrenal_ann <- mutate(adrenal_ann, barcodes=rownames(adrenal_ann))
```


```{r results='asis'}
plot_seurat <- function(file_url='seurat.rds', annotation) {
       sample <- readRDS(file_url) 
       sam_ann <- data.frame(barcodes=colnames(sample), stringsAsFactors = FALSE)
       metadata <- merge(sam_ann, annotation)
       sample$'cell_type' <- metadata$Idents.combined_all_med.
       DimPlot(sample, group.by = 'cell_type' , reduction = 'umap', label = TRUE) + NoLegend()
}
```


## Reproducibility of clusters {.tabset}



### Sample 13363

```{r echo=FALSE}
plot_seurat('../data/13363_med_seurat.rds', adrenal_ann)
```

### Sample 13363

```{r echo=FALSE}
plot_seurat('../data/13567_med_seurat.rds', adrenal_ann)
```

### Sample 13667

```{r echo=FALSE}
plot_seurat('../data/13667_med_seurat.rds', adrenal_ann)
```

### Sample 13952

```{r echo=FALSE}
plot_seurat('../data/13952_med_seurat.rds', adrenal_ann)
```

### Sample 14164

```{r echo=FALSE}
plot_seurat('../data/14164_med_seurat.rds', adrenal_ann)
```

### Sample 14490
```{r echo=FALSE}
plot_seurat('../data/14490_med_seurat.rds', adrenal_ann)
```

### Sample 14627

```{r echo=FALSE}
plot_seurat('../data/14627_med_seurat.rds', adrenal_ann)
```

### Sample 14707

```{r echo=FALSE}
plot_seurat('../data/14707_med_seurat.rds', adrenal_ann)
```

### Sample 14742

```{r echo=FALSE}
plot_seurat('../data/14742_med_seurat.rds', adrenal_ann)
```

### Sample 14766

```{r echo=FALSE}
plot_seurat('../data/14766_med_seurat.rds', adrenal_ann)
```

### Sample 14773

```{r echo=FALSE}
plot_seurat('../data/14773_med_seurat.rds', adrenal_ann)
```

### Sample 14933

```{r echo=FALSE}
plot_seurat('../data/14933_med_seurat.rds', adrenal_ann)
```

### Sample 15084

```{r echo=FALSE}
plot_seurat('../data/15084_med_seurat.rds', adrenal_ann)
```

### Sample 15161

```{r echo=FALSE}
plot_seurat('../data/15161_med_seurat.rds', adrenal_ann)
```


## Batch correction

```{r echo=FALSE}
adrenal <- read_rds('../data/batch_correction_adrenal_medulla_tsne.rds')
by_signature <- adrenal$tsne_coords %>%
                as.data.frame %>%
                rename(tSNE1=V1, tSNE2=V2) %>%
                ggplot(aes(tSNE1, tSNE2, colour = adrenal$clusters)) +
                    geom_point(alpha = 0.4, size = 2) + 
                    theme_classic() +
                    theme(legend.title = element_blank(),
                          legend.position = 'bottom') +
                    ggtitle('By signature')

```

```{r echo=FALSE}
by_dataset <- adrenal$tsne_coords %>%
                as.data.frame %>%
                rename(tSNE1=V1, tSNE2=V2) %>%
                ggplot(aes(tSNE1, tSNE2, colour = adrenal$cell_data$dataset)) +
                    geom_point(alpha = 0.5, size = 1.5) + 
                    theme_classic() +
                    theme(legend.title = element_blank()) +
                    ggtitle('By dataset')

```

```{r echo=FALSE}
by_dataset
```

```{r echo=FALSE}
coords <- adrenal$tsne_coords %>% 
              as.data.frame %>%
              rename(tSNE1=V1, tSNE2=V2) %>%
              mutate(barcodes = rownames(adrenal$tsne_coords))
coords_ann <- merge(coords, adrenal_ann) 

by_cell_type <- coords_ann %>% 
         ggplot(aes(tSNE1, tSNE2, colour = Idents.combined_all_med.)) +
         geom_point(alpha = 0.5, size = 1.5) + 
         theme_classic() +
         theme(legend.title = element_blank(),
               legend.position = 'bottom') +
          ggtitle('By cell type')
```

### Clusters in corrected data

```{r echo=FALSE}
grid.arrange(by_signature, by_cell_type, ncol=2)
```


## Glandulla projection


## Batch correction

```{r echo=FALSE}
## Loading glandulla projection
neuro_seu <- readRDS('../data/batch_correction.rds')
neuro_umap <- RunUMAP(neuro_seu, dims=1:8, reduction = 'iNMF')
DimPlot(neuro_umap, reduction = 'umap', group.by = 'orig.ident')
```


```{r}
## Loading data
file_names <- list.files('../data/intratumoral/', full.names=TRUE)
f_names <- gsub('../data/intratumoral/', '', file_names)
f_names <- gsub('_.*|/', '', f_names)
f_names <- gsub('\\.rds', '', f_names)
f_names

seurat <- lapply(file_names, readRDS)
seurat <- merge(x = seurat[[1]], y = seurat[2:length(seurat)])
saveRDS(seurat, '../data/intratumoral_merged_seurat.rds')

seurat.p <- readRDS('../data/intratumotal_liger_seurat.rds')
seurat.p <- RunUMAP(seurat.p, dims=1:8, reduction = 'iNMF')
DimPlot(seurat.p, group.by = 'orig.ident', reduction = 'umap')
```


